default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    # Install Tuist dependencies
    sh("cd .. && tuist install")
    # Generate project
    sh("cd .. && tuist generate")
    # Parse provisioning profile to get Name and UUID
    profile_path = File.expand_path("../profile.mobileprovision")
    profile = FastlaneCore::ProvisioningProfile.parse(profile_path)
    profile_name = profile["Name"]
    profile_uuid = profile["UUID"]
    
    # Configure Code Signing specifically for the App target
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "Friendly.xcodeproj",
      targets: ["Friendly"],
      profile_name: profile_name,
      profile_uuid: profile_uuid,
      team_id: ENV["APPLE_TEAM_ID"],
      code_sign_identity: "Apple Distribution",
      build_configurations: ["Release"]
    )

    # Build and upload to TestFlight
    build_app(
      workspace: "Friendly.xcworkspace",
      scheme: "Friendly",
      export_method: "app-store",
      xcargs: "CURRENT_PROJECT_VERSION='#{ENV['GITHUB_RUN_NUMBER']}'",
      export_options: {
        method: "app-store",
        provisioningProfiles: {
          "me.y9san9.Friendly" => profile_name
        }
      }
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
